const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  await prisma.product.createMany({
    data: [
      {
        name: "Calvin Klein Crewneck Tee",
        slug: "ck-crewneck-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
        {
        name: "Mark and Spenser shoe",
        slug: "mark-spenser-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 2,
      },
   {
        name: "Straight Fit Denim Jeans",
        slug: "denim-jean-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "Nike Sb",
        slug: "nike-sb-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "Von Dutch cap",
        slug: "von-dutch-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
    
       {
        name: "Air jordan 1 low",
        slug: "air-jordan-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "Charles Thyritt long sleeve Shirt",
        slug: "charles-thyritt-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "New Balance",
        slug: "new-balance-03",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "wrangler Jeans",
        slug: "wrangler-jeans-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "Air Jordan 1",
        slug: "air-jordan-02",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
        {
        name: "Adidas",
        slug: "adidas-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
        {
        name: "Nike SB",
        slug: "nike-sb-04",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
        {
        name: "Nike Air Max",
        slug: "air max-01", 
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "New balance",
        slug: "new-balance-02",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
       {
        name: "Pro Club T shirt ",
        slug: "pro-club-01",
        price: 249.99,
        currency: "GHS",
        images: ["/products/force1c.JPG"],
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
    ],
  });
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
