const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  await prisma.product.createMany({
    data: [
      {
        name: "True religion",
        slug: "ck-crewneck-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905334/IMG_5462.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Mark and Spenser shoe",
        slug: "mark-spenser-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904351/IMG_5400.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 2,
      },
      {
        name: "Straight Fit Denim Jeans",
        slug: "denim-jean-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904715/IMG_5403.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Nike Sb",
        slug: "nike-sb-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904733/IMG_5413.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Von Dutch cap",
        slug: "von-dutch-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904762/IMG_5422.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Air jordan 1 low",
        slug: "air-jordan-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904777/IMG_5432.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Charles Thyritt long sleeve Shirt",
        slug: "charles-thyritt-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904838/IMG_5482.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "New Balance",
        slug: "new-balance-03",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905326/IMG_5459.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "wrangler Jeans",
        slug: "wrangler-jeans-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904817/IMG_5477.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Air Jordan 1",
        slug: "air-jordan-02",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905288/IMG_5438.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Adidas",
        slug: "adidas-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905295/IMG_5443.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Nike SB",
        slug: "nike-sb-04",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905302/IMG_5445.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Nike Air Max",
        slug: "air-max-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905309/IMG_5448.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "New balance",
        slug: "new-balance-02",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788905283/IMG_5437.webp",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Pro Club T shirt",
        slug: "pro-club-01",
        price: 249.99,
        currency: "GHS",
        images: "https://res.cloudinary.com/zxiwczte/image/upload/v1788904853/IMG_5484.jpg",
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
    ],
    skipDuplicates: true, // avoids a hard failure (and empty insert) if a slug already exists
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
