// prisma/seed.js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const result = await prisma.product.createMany({
    data: [
      {
        name: "True Religion",
        slug: "ck-crewneck-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905334/IMG_5462.webp"], // ✅ array
        description: "Classic crewneck tee in soft cotton jersey.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
      {
        name: "Mark and Spencer Shoe",
        slug: "mark-spenser-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904351/IMG_5400.webp"],
        description: "Premium leather shoe from Mark and Spencer.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "Brown", "White"],
        category: "Shoes",
        stock: 2,
      },
      {
        name: "Straight Fit Denim Jeans",
        slug: "denim-jean-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904715/IMG_5403.webp"],
        description: "Straight fit denim jeans with a comfortable cut.",
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Blue", "Black", "Grey"],
        category: "Jeans",
        stock: 20,
      },
      {
        name: "Nike SB",
        slug: "nike-sb-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904733/IMG_5413.webp"],
        description: "Nike SB skateboarding shoes with durable sole.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "White", "Grey"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Von Dutch Cap",
        slug: "von-dutch-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904762/IMG_5422.webp"],
        description: "Iconic Von Dutch trucker cap.",
        sizes: ["One Size"],
        colors: ["Black", "White", "Grey"],
        category: "Accessories",
        stock: 20,
      },
      {
        name: "Air Jordan 1 Low",
        slug: "air-jordan-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904777/IMG_5432.webp"],
        description: "Air Jordan 1 Low in classic colourway.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "White", "Red"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Charles Tyrwhitt Long Sleeve Shirt",
        slug: "charles-thyritt-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904838/IMG_5482.webp"],
        description: "Elegant long sleeve shirt from Charles Tyrwhitt.",
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Blue", "Pink"],
        category: "Shirts",
        stock: 20,
      },
      {
        name: "New Balance 03",
        slug: "new-balance-03",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905326/IMG_5459.webp"],
        description: "New Balance sneakers with superior cushioning.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["White", "Grey", "Navy"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Wrangler Jeans",
        slug: "wrangler-jeans-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904817/IMG_5477.webp"],
        description: "Rugged Wrangler jeans built to last.",
        sizes: ["28", "30", "32", "34", "36"],
        colors: ["Blue", "Black"],
        category: "Jeans",
        stock: 20,
      },
      {
        name: "Air Jordan 1",
        slug: "air-jordan-02",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905288/IMG_5438.webp"],
        description: "Iconic Air Jordan 1 high-top sneaker.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "White", "Red"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Adidas",
        slug: "adidas-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905295/IMG_5443.webp"],
        description: "Adidas sneakers with classic three-stripe design.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "White"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Nike SB",
        slug: "nike-sb-04",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905302/IMG_5445.webp"],
        description: "Nike SB with grippy outsole for skateboarding.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "White"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Nike Air Max",
        slug: "air-max-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905309/IMG_5448.webp"],
        description: "Nike Air Max with visible air unit for comfort.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["Black", "White", "Red"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "New Balance 02",
        slug: "new-balance-02",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788905283/IMG_5437.webp"],
        description: "New Balance everyday trainer with memory foam insole.",
        sizes: ["40", "41", "42", "43", "44"],
        colors: ["White", "Grey"],
        category: "Shoes",
        stock: 20,
      },
      {
        name: "Pro Club T-Shirt",
        slug: "pro-club-01",
        price: 249.99,
        currency: "GHS",
        images: ["https://res.cloudinary.com/zxiwczte/image/upload/v1788904853/IMG_5484.jpg"],
        description: "Heavyweight Pro Club crewneck tee.",
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black", "White", "Grey"],
        category: "T-Shirts",
        stock: 20,
      },
    ],
    skipDuplicates: true,
  });

  console.log(`✅ Seed complete — ${result.count} products inserted.`);
}

main()
  .catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());